doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '15'
        driver: 'pdo_pgsql'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MessageView:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Message/Query/View'
                prefix: 'App\Infrastructure\Message\Query\View'
                alias: MessageView
